name: npm-publish

on:
  branches:
    - master

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.0.0

      - name: Build dist.
        run: |
          npm install
          npm run build

      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Config for secret: NPM_AUTH_TOKEN is required.
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
