name: npm-publish

on:
  push:
    tags: '*'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.0.0

      - name: Build dist.
        run: |
          npm install
          npm run build

      - name: Publish to NPM.
        run: npm publish --access public
        env:
          # Config for secret: NPM_AUTH_TOKEN is required.
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
